// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../../components/plasmic/copy_of_sips_by_website/PlasmicGlobalVariant__Screen";
import { PlasmicZHome20220806 } from "../../components/plasmic/copy_of_sips_by_website/PlasmicZHome20220806";
import { useRouter } from "next/router";

function ZHome20220806() {
  // Use PlasmicZHome20220806 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicZHome20220806 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicZHome20220806 is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <ph.PageParamsProvider params={useRouter().query} query={useRouter().query}>
      <PlasmicZHome20220806 />
    </ph.PageParamsProvider>
  );
}

export default ZHome20220806;
