// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s9FtU1QqNRpfuTCYMk46sz
// Component: JqPwgtq3frM4H
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PageRow from "../../PageRow"; // plasmic-import: AKAM4dN1Fw/component
import Button from "../../Button"; // plasmic-import: sw7k7LkFBTC/component
import { Image } from "../../../../components/image"; // plasmic-import: Kwarv--gNegupF/codeComponent
import { Carousel } from "../../../../components/carousel"; // plasmic-import: VJ9-SKBWJjSYFK/codeComponent
import QuotationV1 from "../../QuotationV1"; // plasmic-import: _Z8xXR8LUJ/component

import { useScreenVariants as useScreenVariants_6PiZsruRybCC } from "../sips_by_design_system/PlasmicGlobalVariant__Screen"; // plasmic-import: 6piZsruRybC-C/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_sips_by_design_system_css from "../sips_by_design_system/plasmic_sips_by_design_system.module.css"; // plasmic-import: mrgn3VC2r6s7VB3wKPe7xp/projectcss
import projectcss from "./plasmic_copy_of_sips_by_website.module.css"; // plasmic-import: s9FtU1QqNRpfuTCYMk46sz/projectcss
import sty from "./PlasmicXMDot.module.css"; // plasmic-import: JqPwgtq3frM4H/css

import ChecksvgIcon from "../sips_by_design_system/icons/PlasmicIcon__Checksvg"; // plasmic-import: cFH4ysruE7k/icon
import IconIcon from "../sips_by_design_system/icons/PlasmicIcon__Icon"; // plasmic-import: XuqNxn7mH8d/icon
import Icon3Icon from "../sips_by_design_system/icons/PlasmicIcon__Icon3"; // plasmic-import: QH3TGD-PAa/icon

export type PlasmicXMDot__VariantMembers = {};

export type PlasmicXMDot__VariantsArgs = {};
type VariantPropType = keyof PlasmicXMDot__VariantsArgs;
export const PlasmicXMDot__VariantProps = new Array<VariantPropType>();

export type PlasmicXMDot__ArgsType = {};
type ArgPropType = keyof PlasmicXMDot__ArgsType;
export const PlasmicXMDot__ArgProps = new Array<ArgPropType>();

export type PlasmicXMDot__OverridesType = {
  root?: p.Flex<"div">;
  hero?: p.Flex<"section">;
  p?: p.Flex<"p">;
  mobileImage?: p.Flex<typeof p.PlasmicImg>;
  logos?: p.Flex<"section">;
  whatYouGet?: p.Flex<"section">;
  howItWorks?: p.Flex<"section">;
  dualCta?: p.Flex<"section">;
  howItWorks2?: p.Flex<"section">;
  dualCta2?: p.Flex<"section">;
  brands?: p.Flex<"section">;
  privacy?: p.Flex<"section">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultXMDotProps {}

function PlasmicXMDot__RenderFunc(props: {
  variants: PlasmicXMDot__VariantsArgs;
  args: PlasmicXMDot__ArgsType;
  overrides: PlasmicXMDot__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6PiZsruRybCC()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_sips_by_design_system_css.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__lw3Jg)}>
              <PageRow
                className={classNames("__wab_instance", sty.pageRow__kgHmF)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__rrny7)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__f2UNt
                    )}
                  >
                    {"Get a tea box tailored to you."}
                  </h1>

                  <p
                    data-plasmic-name={"p"}
                    data-plasmic-override={overrides.p}
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.__wab_text,
                      sty.p
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"4 teas, $16 monthly, "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"free shipping"}
                      </span>
                    </React.Fragment>
                  </p>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__opwEa)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ioHck
                      )}
                      link={"/account/register" as const}
                    >
                      {"Get Your Box"}
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___8AeE
                      )}
                      link={"/pages/lp-gift" as const}
                      variant={"secondary" as const}
                    >
                      {"Give a Gift"}
                    </Button>
                  </p.Stack>
                </p.Stack>
              </PageRow>
            </div>

            {(
              hasVariant(globalVariants, "screen", "tabletLandscape")
                ? true
                : true
            ) ? (
              <p.PlasmicImg
                data-plasmic-name={"mobileImage"}
                data-plasmic-override={overrides.mobileImage}
                alt={""}
                className={classNames(sty.mobileImage)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/copy_of_sips_by_website/images/bgSipsByBoxSippingTeaMobile70Jpg.jpeg",
                  fullWidth: 1600,
                  fullHeight: 1060,
                  aspectRatio: undefined
                }}
              />
            ) : null}
          </section>

          {true ? (
            <section
              data-plasmic-name={"logos"}
              data-plasmic-override={overrides.logos}
              className={classNames(projectcss.all, sty.logos)}
            >
              <PageRow
                className={classNames("__wab_instance", sty.pageRow__ydhyk)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__imjul)}>
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__k3TZf)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__yLol)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tabletPortrait")
                            ? ("162px" as const)
                            : ("140px" as const)
                        }
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/logo-buzzfeed-black-opt.svg?v=1639435144" as const
                        }
                      />
                    </div>
                  ) : null}

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__g64Jg)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__folI)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/logo-nbc-news-black-opt.svg?v=1639437059" as const
                        }
                      />
                    </div>
                  ) : null}

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__q8IgA)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mmjCx)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/logo-real-simple-black-opt.svg?v=1639435144" as const
                        }
                      />
                    </div>
                  ) : null}

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__adYwp)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__lgfZ)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tabletPortrait")
                            ? ("159px" as const)
                            : ("129px" as const)
                        }
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/logo-womens-health-black-opt.svg?v=1639435144" as const
                        }
                      />
                    </div>
                  ) : null}
                </div>
              </PageRow>
            </section>
          ) : null}

          <section
            data-plasmic-name={"whatYouGet"}
            data-plasmic-override={overrides.whatYouGet}
            className={classNames(projectcss.all, sty.whatYouGet)}
          >
            <PageRow
              className={classNames("__wab_instance", sty.pageRow__kabVq)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__cw9Zi
                )}
              >
                {"What You Get"}
              </h2>

              <div className={classNames(projectcss.all, sty.freeBox__myvkB)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fFlnA)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__knUxm)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__dDl3M)}
                      displayHeight={"45px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"45px" as const}
                      loading={"lazy" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/illustration-tea-bag.svg?v=1636499860" as const
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6GUfk
                      )}
                    >
                      {"Four new teas curated just for you every month"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__oi1E)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__viS)}
                      displayHeight={"45px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"45px" as const}
                      loading={"lazy" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/illustration-tea-pot.svg?v=1636499860" as const
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y5Oh
                      )}
                    >
                      {"Access to exclusive tea brands only on Sips by"}
                    </div>
                  </div>
                </p.Stack>

                {(
                  hasVariant(globalVariants, "screen", "tabletLandscape")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2J5Im)}
                  >
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image___8J2G)}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/animation-sips-by-box-60.gif?v=1636653547" as const
                      }
                    />
                  </div>
                ) : null}

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___0Erq6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dWOo)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iQwM)}
                        displayHeight={"45px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"45px" as const}
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/illustration-teacup.svg?v=1636499860" as const
                        }
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tSo7M
                        )}
                      >
                        {"Reusable tea filters for loose teas + brewing tips"}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__mx037)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__enUtQ)}
                        displayHeight={"45px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"45px" as const}
                        loading={"lazy" as const}
                        src={
                          "https://cdn.shopify.com/s/files/1/1677/2601/files/illustration-tea-leaves.svg?v=1636499860" as const
                        }
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__khPro
                        )}
                      >
                        {"Early access to product launches and sales"}
                      </div>
                    </div>
                  </p.Stack>
                ) : null}

                {(
                  hasVariant(globalVariants, "screen", "tabletLandscape")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ptzYv)}
                  >
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__yDfYr)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/animation-sips-by-box-60.gif?v=1636653547" as const
                      }
                      width={"300px" as const}
                    />
                  </div>
                ) : null}
              </div>
            </PageRow>
          </section>

          <section
            data-plasmic-name={"howItWorks"}
            data-plasmic-override={overrides.howItWorks}
            className={classNames(projectcss.all, sty.howItWorks)}
          >
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__wkDzH
              )}
            >
              {"How It Works"}
            </h2>

            <PageRow
              className={classNames("__wab_instance", sty.pageRow__yHFq)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__pvLRr)}>
                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__z2Ydb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jhTej
                      )}
                    >
                      {"1"}
                    </div>

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__smy0J
                      )}
                    >
                      {"Take the Quiz"}
                    </h1>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kZjUa
                      )}
                    >
                      {
                        "Take the tea profile quiz to discover your favorite teas. It covers caffeine, flavor, loose vs. bagged, and dietary preferences."
                      }
                    </div>
                  </div>
                ) : null}

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hWeW)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y2Osq
                      )}
                    >
                      {"2"}
                    </div>

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__twby3
                      )}
                    >
                      {"Get Your Box"}
                    </h1>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cnc7H
                      )}
                    >
                      {
                        "Our Steep technology learns your profile to select personalized teas uniquely for you and delivers them to your door"
                      }
                    </div>
                  </div>
                ) : null}

                {true ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wxBgb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1R73O
                      )}
                    >
                      {"3"}
                    </div>

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__k3JbM
                      )}
                    >
                      {"Rate Your Teas"}
                    </h1>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l7Uge
                      )}
                    >
                      {
                        "Steep will learn to find you even better matches that make you sip and say, “Ahhh” for months to come"
                      }
                    </div>
                  </div>
                ) : null}
              </div>
            </PageRow>
          </section>

          <section
            data-plasmic-name={"dualCta"}
            data-plasmic-override={overrides.dualCta}
            className={classNames(projectcss.all, sty.dualCta)}
          >
            <PageRow
              className={classNames("__wab_instance", sty.pageRow__wQrb)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__eOrn8)}>
                <Button
                  className={classNames("__wab_instance", sty.button__oTc9L)}
                  link={"/account/register" as const}
                >
                  {"Get Your Box"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__nFjFa)}
                  endIcon={
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__ny5Of)}
                      role={"img"}
                    />
                  }
                  link={"/pages/lp-gift" as const}
                  variant={"secondary" as const}
                >
                  {"Give a Gift"}
                </Button>
              </div>
            </PageRow>
          </section>

          <section
            data-plasmic-name={"howItWorks2"}
            data-plasmic-override={overrides.howItWorks2}
            className={classNames(projectcss.all, sty.howItWorks2)}
          >
            <PageRow
              className={classNames("__wab_instance", sty.pageRow__n7Go0)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__dnSa
                )}
              >
                {"Join the Best Tea Club"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0IaIf
                )}
              >
                {
                  "500,000 tea people and counting trust Sips by to find their perfect tea matches."
                }
              </div>

              <Carousel
                className={classNames("__wab_instance", sty.carousel__yaaD)}
                lazyLoad={true}
                navigation={false}
                navigationButtonAlpha={0.05 as const}
                navigationOnTop={false}
                pagination={true}
                paginationOnTop={false}
                random={false}
                slidesPerView={{
                  default: 1,
                  portraitTablets: 2,
                  landscapeTablets: 3
                }}
                spaceBetween={15 as const}
              >
                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1__vUbAb
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__hcF38)}
                      crop={"" as const}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/SummerBox.jpg?3742" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "It’s a new month, which means new teas! They hit this one out of the park!"
                  }
                >
                  {"Angela in California"}
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1__hkdrd
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__rh5RK)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/CouplesBox.jpg?3742" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "Month number four of obsessing over my Sips by Box! Boy, is it good!"
                  }
                >
                  {"Shelby in Texas"}
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1___5Rtkp
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames(
                        "__wab_instance",
                        sty.image___57CP4
                      )}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/LifestyleBox.jpg?3742" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "Love the packaging and variety each month. Thank you Sips by!"
                  }
                >
                  {"Matt in Oregon"}
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1__gXcif
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__wCrgA)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/OutdoorBox.jpg?3742" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "I get brands I already love, have been dying to try, and never heard of!"
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hVask
                    )}
                  >
                    {"Renee in New York"}
                  </div>
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1__tVtLc
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__aPNet)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/MugPhoto.jpg?3742" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "So in love with this service and the brands! My teas were perfect!"
                  }
                >
                  {"Mary in Missouri"}
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1___1FpDd
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__gto4O)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/WinterBox.jpg?3743" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "Sips by knows me better than I know myself! They know just what to send."
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__suX4
                    )}
                  >
                    {"Allie in Colorado"}
                  </div>
                </QuotationV1>

                <QuotationV1
                  className={classNames(
                    "__wab_instance",
                    sty.quotationV1___0PknC
                  )}
                  slot={
                    <Image
                      altText={"" as const}
                      className={classNames("__wab_instance", sty.image__qt02)}
                      height={"" as const}
                      src={
                        "https://cdn.shopify.com/s/files/1/1677/2601/files/AutumnBox.jpg?3743" as const
                      }
                      width={"100%" as const}
                    />
                  }
                  slot3={
                    "This box fits me perfectly! Love the range of new teas to try."
                  }
                >
                  {"Philomena in Kentucky"}
                </QuotationV1>
              </Carousel>
            </PageRow>
          </section>

          <section
            data-plasmic-name={"dualCta2"}
            data-plasmic-override={overrides.dualCta2}
            className={classNames(projectcss.all, sty.dualCta2)}
          >
            <PageRow
              className={classNames("__wab_instance", sty.pageRow___4Q9Cb)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__qDrVb)}>
                <Button
                  className={classNames("__wab_instance", sty.button__rQjXi)}
                  link={"/account/register" as const}
                >
                  {"Get Your Box"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__eTy3H)}
                  endIcon={
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__kimn9)}
                      role={"img"}
                    />
                  }
                  link={"/pages/lp-gift" as const}
                  variant={"secondary" as const}
                >
                  {"Give a Gift"}
                </Button>
              </div>
            </PageRow>
          </section>

          {true ? (
            <section
              data-plasmic-name={"brands"}
              data-plasmic-override={overrides.brands}
              className={classNames(projectcss.all, sty.brands)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ukvYm
                )}
              >
                {"150+ Brands"}
              </h2>

              <PageRow
                className={classNames("__wab_instance", sty.pageRow___7InC)}
              >
                <Carousel
                  className={classNames("__wab_instance", sty.carousel___1XtMr)}
                  lazyLoad={
                    hasVariant(globalVariants, "screen", "tabletPortrait")
                      ? true
                      : true
                  }
                  navigation={false}
                  navigationButtonAlpha={0.05 as const}
                  navigationOnTop={false}
                  pagination={true}
                  paginationOnTop={false}
                  random={false}
                  slidesPerView={
                    hasVariant(globalVariants, "screen", "tabletLandscape")
                      ? { default: 1, portraitTablets: 2, landscapeTablets: 3 }
                      : hasVariant(globalVariants, "screen", "tabletPortrait")
                      ? { default: 1, portraitTablets: 2, landscapeTablets: 3 }
                      : { default: 1, portraitTablets: 2, landscapeTablets: 3 }
                  }
                  spaceBetween={15 as const}
                >
                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__poX6V)}
                    crop={"" as const}
                    height={"" as const}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/AhmadTea_400x400@2x.jpg?v=1614366756" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__oAsyM)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/Choice1_400x400@2x.jpg?10838374313174502166" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__cC83B)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/MiracleTree_400x400@2x.jpg?4621997498648330880" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__v2A1P)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/OrganicIndia1_400x400@2x.jpg?5073180652762406678" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__zz3Pm)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/StashTea_400x400@2x.jpg?v=1567701555" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__fUy5D)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/tiny_bee_tea1_400x400@2x.png.jpg?v=1623701249" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__qpd45)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/tiny_bee_tea1_400x400@2x.png.jpg?v=1623701249" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__uvjyu)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/SHANGRI_LA_BRAND_BADGE_400x400@2x.png.jpg?v=1635345116" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image___99Cyr)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/AugustUncommon_400x400@2x.png.jpg?v=1614365729" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image___18Fne)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/Nepal_Tea_400x400@2x.jpg?1862258087882541788" as const
                    }
                  />

                  <Image
                    altText={"" as const}
                    className={classNames("__wab_instance", sty.image__zoEMs)}
                    src={
                      "https://cdn.shopify.com/s/files/1/1677/2601/files/brand-partner-tealyra_400x400@2x.jpg?v=1637712822" as const
                    }
                  />
                </Carousel>
              </PageRow>
            </section>
          ) : null}

          {true ? (
            <section
              data-plasmic-name={"privacy"}
              data-plasmic-override={overrides.privacy}
              className={classNames(projectcss.all, sty.privacy)}
            >
              <p.PlasmicLink
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={"/pages/privacy-policy" as const}
                platform={"nextjs"}
                target={"_blank" as const}
              >
                {"Privacy Policy"}
              </p.PlasmicLink>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "hero",
    "p",
    "mobileImage",
    "logos",
    "whatYouGet",
    "howItWorks",
    "dualCta",
    "howItWorks2",
    "dualCta2",
    "brands",
    "privacy",
    "link"
  ],
  hero: ["hero", "p", "mobileImage"],
  p: ["p"],
  mobileImage: ["mobileImage"],
  logos: ["logos"],
  whatYouGet: ["whatYouGet"],
  howItWorks: ["howItWorks"],
  dualCta: ["dualCta"],
  howItWorks2: ["howItWorks2"],
  dualCta2: ["dualCta2"],
  brands: ["brands"],
  privacy: ["privacy", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  hero: "section";
  p: "p";
  mobileImage: typeof p.PlasmicImg;
  logos: "section";
  whatYouGet: "section";
  howItWorks: "section";
  dualCta: "section";
  howItWorks2: "section";
  dualCta2: "section";
  brands: "section";
  privacy: "section";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicXMDot__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicXMDot__VariantsArgs;
    args?: PlasmicXMDot__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicXMDot__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicXMDot__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicXMDot__ArgProps,
          internalVariantPropNames: PlasmicXMDot__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicXMDot__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicXMDot";
  } else {
    func.displayName = `PlasmicXMDot.${nodeName}`;
  }
  return func;
}

export const PlasmicXMDot = Object.assign(
  // Top-level PlasmicXMDot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    hero: makeNodeComponent("hero"),
    p: makeNodeComponent("p"),
    mobileImage: makeNodeComponent("mobileImage"),
    logos: makeNodeComponent("logos"),
    whatYouGet: makeNodeComponent("whatYouGet"),
    howItWorks: makeNodeComponent("howItWorks"),
    dualCta: makeNodeComponent("dualCta"),
    howItWorks2: makeNodeComponent("howItWorks2"),
    dualCta2: makeNodeComponent("dualCta2"),
    brands: makeNodeComponent("brands"),
    privacy: makeNodeComponent("privacy"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicXMDot
    internalVariantProps: PlasmicXMDot__VariantProps,
    internalArgProps: PlasmicXMDot__ArgProps
  }
);

export default PlasmicXMDot;
/* prettier-ignore-end */
