// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/copy_of_sips_by_website/PlasmicGlobalVariant__Screen";
import { Plasmic_3WaysToGift } from "../components/plasmic/copy_of_sips_by_website/Plasmic_3WaysToGift";
import { useRouter } from "next/router";

function _3WaysToGift() {
  // Use Plasmic_3WaysToGift to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic_3WaysToGift are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmic_3WaysToGift is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <ph.PageParamsProvider params={useRouter().query} query={useRouter().query}>
      <Plasmic_3WaysToGift />
    </ph.PageParamsProvider>
  );
}

export default _3WaysToGift;
